import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";

const Home: NextPage = () => {
  const linklist = [
    {
      href: "/account/login",
      label: "login",
    },
    {
      href: "/scraper-results",
      label: "results",
    },
  ];
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        {linklist.map(({ href, label }) => (
          <Link href={href} key={label}>
            {label}
          </Link>
        ))}
      </main>
    </div>
  );
};

export default Home;
